build : quadtree

quadtree : main.c task01.c task02.c task03.c bonus.c matrix.c count.c create.c h_and_v.c bfs.c other_functions.c
	gcc -g -Wall main.c task01.c task02.c task03.c bonus.c matrix.c count.c create.c h_and_v.c bfs.c other_functions.c -o quadtree -lm

clean:
	rm -f quadtree
